### ISSUE TITLE
Object.observe(CRUD.stats: not working on mobile

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#10]
Hello SchizoDuckie,

The following code works fine on Chrome but not on the mobile:
Any idea where to look for?

```
        Object.observe(CRUD.stats, function(newValues) {
           progress.innerHTML = Math.floor((CRUD.stats.writesExecuted / CRUD.stats.writesQueued) * 100);
           writesQueued.innerHTML = CRUD.stats.writesQueued;
           writesExecuted.innerHTML = CRUD.stats.writesExecuted; 
            if(CRUD.stats.writesQueued == CRUD.stats.writesExecuted) {
                updateCount();
            }
        });

```

Kind regards,
Mario

**Comment by SchizoDuckie** [comment]
Object.observe is not available on mobile (and also deprecated).

In a pending release version of CRUD.js i've added getters and setters that allow hooking a callback into the stats process:

![image](https://cloud.githubusercontent.com/assets/111710/23836273/03c08320-0776-11e7-8b95-f6f893de7410.png)
