### ISSUE TITLE
Does CRUD.Find support WHERE column_name IN (value1,value2,...);

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#11]
Hello SchizoDuckie,

I tried it but CRUD.Find does not seem to support: WHERE column_name IN (value1,value2,...)

If it should please tell me how and if not do we have a workaround?

Kind regards,
Mario

**Comment by SchizoDuckie** [comment]
You can pass a custom where clause in the query (note that this doesnt SQL parameter binding, handle with care)

```
   var filter = ['Episodes.firstaired > "' + start + '" AND Episodes.ID_Episode IN ("+implode(',', IdList)+ ")"];
   return CRUD.Find('Episode', filter).then(function(ret) { /** results */});
```
