### ISSUE TITLE
Can migration trigger a javascript function?

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#15]
Hello SchizoDuckie,

I need to alter a table and fire a one time function after the migration.
Is this possible?

Kind regards,
Mario

**Comment by SchizoDuckie** [comment]
There is no generic method implemented to do this currently.

You can wait for CRUD.SqliteAdapter.initializing to turn from false to true to execute a callback if you need to execute stuff ASAP, this is also how it works internally:

![image](https://cloud.githubusercontent.com/assets/111710/23836233/7f563062-0775-11e7-9460-a61ee3be79d4.png)
