### ISSUE TITLE
Joints

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#6]
Hello SchizoDuckie,

(Hope this is a Crud question:-)
I want to read x fields from table1 and y fields from a related table 2 (1 on 1)
(And as a result show them in a table.)
How do we do this the crud way?

Kind regards,
Mario

**Comment by SchizoDuckie** [comment]
You're talking about partial results, something that CRUD.js does not support as it's a nightmare to implement with a huge amount of implementations.

use CRUD.ExecuteQuery to fetch a custom resultset.
