### ISSUE TITLE
CRUD.FindCount is not a function

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#7]
Hello SchizoDuckie,

Question: Should this work?
It works in your demo: http://jsfiddle.net/SchizoDuckie/p7kta1mv/
But I am not sure this is old source.
But I get CRUD.FindCount is not a function (tried in and out quotes)

```
CRUD.FindCount('Food').then(function(count) {
    total.innerHTML = count;  
});

```

Kind regards,
Mario

**Comment by SchizoDuckie** [comment]
Correct, FindCount has been removed in favour of a custom CRUD.ExecuteQuery
