### ISSUE TITLE
Remote server synchronization

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#8]
Hello SchizoDuckie,

Our present project is a sharepoint mobile extension with which we use the SharePoint API to sync the data from and to remote.
For another project we are free to choose a remote server sync. Do you have experience and can advise a solution that works good and can scale up to large data traffic?

Kind regards,
Mario

**Comment by SchizoDuckie** [comment]
sorry, that is beyond the scope of the support i'm willing to deliver on this.
