### ISSUE TITLE
Using FIND or FINDONE on related tables

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [SchizoDuckie/CreateReadUpdateDelete.js#9]
Hello SchizoDuckie,

Adding a relationship to a table probably modifies the object structure?
I ask because after adding the relationship below function findFood() only returns objects and I don't know how to get inside the objects.
The function findFoodFav = the related table and also only return an [object Object]

```
function findFood(){
    CRUD.Find('Food', {}, { limit: '0,10000' }).then(function(results) {
        return results.map(function(entity) {return entity.asObject()})
        }).then(function(result){
            console.log(JSON.stringify("Food: "+result));
    });
}

function findFoodFav(){     
    CRUD.FindOne('Food', { ID_Food: 3}).then(function(food) {
        food.Find('FoodFav').then(function(foodfav) {
            console.log("FoodFav: "+foodfav);
        });
    });
}
```

Can you advise?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Hello SchizoDuckie,

I think I am moving forward with my trial and errors. But Can you tell me how to do a connection to an existing actor?

```
CRUD.setAdapter(new CRUD.SQLiteAdapter('createreadupdatedelete_single', {
    estimatedSize: 25 * 1024 * 1024
})).then(function() {

    var cptn = new Role();
    cptn.name = 'Captain Jack Sparrow';

    var actor = new Actor();
    actor.firstName = 'Johnny';
    actor.lastName = 'Depp';
    actor.gender = 'm';

    cptn.Connect(actor);

});
```

**Comment by SchizoDuckie** [comment]
Please refer to the updated docs here : https://github.com/SchizoDuckie/CreateReadUpdateDelete.js
